/* ==========================================================================
   PHOTO GALLERY - generated by tools/update-gallery.ps1
   Add captions between the quotes; re-running the script overwrites this file.
   ========================================================================== */
window.GALLERY = [
  { src: "images/gallery/web/IMG_20251215_112519.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20251217_122111.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20251223_211024.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20251230_124704_2.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20260104_183100.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20260117_185500_2.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20260213_171244.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20260222_130506.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20260307_172812.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20260403_131011_2.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20260403_134145_2.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20260424_181807.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20260427_124801.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20260523_165803.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20260614_095909_2.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20260725_193406_2.jpg", caption: "" },
  { src: "images/gallery/web/IMG_20260802_124859_2.jpg", caption: "" },
];