# Rebuilds js/gallery.js from the photos in images/gallery/ and makes fast,
# web-sized copies of each photo in images/gallery/web/ (originals are untouched).
#
# Usage (from the project folder):
#   powershell -ExecutionPolicy Bypass -File tools\update-gallery.ps1
#
# Captions come from file names: "02-sunset-at-the-lodge.jpg" -> "Sunset at the lodge".
# Camera names such as IMG_20260222_130506.jpg get no caption.
# Photos appear in file-name order, so prefix names with 01-, 02- ... to control the order.

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$root    = Split-Path -Parent $PSScriptRoot
$folder  = Join-Path $root "images\gallery"
$webDir  = Join-Path $folder "web"
$outFile = Join-Path $root "js\gallery.js"
$exts    = @(".jpg", ".jpeg", ".png", ".webp")
$maxSize = 1600

New-Item -ItemType Directory -Force $webDir | Out-Null
$jpegCodec = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() | Where-Object { $_.MimeType -eq "image/jpeg" }
$quality = New-Object System.Drawing.Imaging.EncoderParameters 1
$quality.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter ([System.Drawing.Imaging.Encoder]::Quality), 82L

function Save-WebCopy($source, $target) {
  $img = [System.Drawing.Image]::FromFile($source)
  try {
    # Apply the phone's EXIF rotation so portrait photos stay upright
    if ($img.PropertyIdList -contains 0x0112) {
      switch ($img.GetPropertyItem(0x0112).Value[0]) {
        3 { $img.RotateFlip([System.Drawing.RotateFlipType]::Rotate180FlipNone) }
        6 { $img.RotateFlip([System.Drawing.RotateFlipType]::Rotate90FlipNone) }
        8 { $img.RotateFlip([System.Drawing.RotateFlipType]::Rotate270FlipNone) }
      }
    }
    $scale = [Math]::Min([double]1, [double]$maxSize / [Math]::Max($img.Width, $img.Height))
    $w = [int]($img.Width * $scale); $h = [int]($img.Height * $scale)
    $bmp = New-Object System.Drawing.Bitmap $w, $h
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $g.DrawImage($img, 0, 0, $w, $h)
    $g.Dispose()
    $bmp.Save($target, $jpegCodec, $quality)
    $bmp.Dispose()
  } finally { $img.Dispose() }
}

$photos = Get-ChildItem -Path $folder -File |
  Where-Object { $exts -contains $_.Extension.ToLower() } |
  Sort-Object Name

$lines = foreach ($p in $photos) {
  $webName = [IO.Path]::GetFileNameWithoutExtension($p.Name) -replace '[^\w\-]', '_'
  $webName = "$webName.jpg"
  $webPath = Join-Path $webDir $webName
  if (-not (Test-Path $webPath) -or (Get-Item $webPath).LastWriteTime -lt $p.LastWriteTime) {
    Save-WebCopy $p.FullName $webPath
  }

  $base = [IO.Path]::GetFileNameWithoutExtension($p.Name)
  if ($base -match '^(IMG|DSC|PXL|DCIM|VID|Photo|WhatsApp)[\W_]*\d') { $caption = "" }
  else {
    $caption = $base -replace '^\d+[-_ ]*', '' -replace '[-_]+', ' '
    if ($caption.Length -gt 0) { $caption = $caption.Substring(0, 1).ToUpper() + $caption.Substring(1) }
    $caption = $caption -replace '"', '\"'
  }
  "  { src: `"images/gallery/web/$webName`", caption: `"$caption`" },"
}

$content = @"
/* ==========================================================================
   PHOTO GALLERY - generated by tools/update-gallery.ps1
   Add captions between the quotes; re-running the script overwrites this file.
   ========================================================================== */
window.GALLERY = [
$($lines -join "`n")
];
"@

[IO.File]::WriteAllText($outFile, $content, (New-Object System.Text.UTF8Encoding $false))
Write-Host "Added $($photos.Count) photo(s) to js/gallery.js (web copies in images/gallery/web)"
